name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: asile12/auto-labeler@v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
